source "https://rubygems.org"
ruby '2.4.3'

group :production do
  gem 'unicorn'
  gem 'unicorn-worker-killer'
end

gem 'sinatra'
gem 'sinatra-reloader'
gem 'haml'
gem 'sinatra-partial'
gem 'sinatra-support'
gem 'sinatra-flash'
gem 'sinatra-contrib'
gem 'will_paginate', '~> 3.1.1'
gem 'sass'
gem 'sequel', '4.39.0'
gem 'pg', '0.21.0'
gem 'logger'
gem 'i18n'
gem 'sinatra-sequel', '0.9.0'
gem 'rack'
gem 'kramdown'
gem 'actionview'
gem 'activesupport'
gem 'privatbank'
gem 'bacon'
gem 'version'
gem 'rake'
gem 'require_all'
gem 'faraday'
gem 'faraday_middleware'
gem 'twemoji'
gem 'socksify'
gem 'mechanize'
gem 'open_exchange_rates'
gem 'telegram-bot-ruby'
gem 'colorize'
gem 'geocoder'
gem 'money'
gem 'google_currency'
gem 'russian'
gem 'sequel-pg-comment'
gem 'hashids'
gem 'base62-rb'
gem 'time_diff'
gem 'thin'
gem 'ruby-hidden-service'
gem 'cloudinary'
gem 'btce'
gem 'rack-timeout'
gem 'hash_syntax'
gem 'block_io'
gem 'sentry-raven'
gem 'fog'
gem 'ezcrypto'
gem 'tor'
gem 'gruff'
gem 'sinatra-captcha'
gem 'public_suffix'
gem 'bestchange_rates', :git => "git://github.com/harmaty/bestchange_rates.git"